### PR TITLE
installed font awesome

### PR DESCRIPTION
**Pull request by Newton-Ephraim**

### CODE REVIEW

**Comment by Newton-Ephraim** [comment]
Good morning ofofon, kindly check to see if i installed the font awesome properly

**Review by KoneeVibes — CHANGES_REQUESTED** [review]
Good morning Newton,

Thanks for the good work.

Please here are a few concerns.

1. How do we use this? 
`<FontAwesomeIcon icon={faEnvelope} />` or `<i class="fa-solid fa-star"></i>`

2. What material/resource did you use as a guide for this? Have you looked at the font awesome docs here - [[https://docs.fontawesome.com/web/use-with/react/](url)]

3. Please I suggest you uninstall everything you have installed and re-install, this time guided by the docs I have just shared so that we don't run into dependencies conflict when we start developing. If you have any issues, I can get on a call with you.

Thank and please let's close this today.

Goodluck!

**Comment by Newton-Ephraim** [comment]
Good evening ofofon, kindly confirm.

**Review by KoneeVibes — APPROVED** [review]
This is good. Thank you very much.

**Pull request merged**
