### PR TITLE
Dev4

### PR DESCRIPTION
**Pull request by Newton-Ephraim**
abeg no vex say e been take so long, i am a rubbish boy lol. abeg check for corrections, so i round it up tomorrow

### CODE REVIEW

**Comment by KoneeVibes** [comment]
I'd look at it by the weekend and revert. As you can imagine, this NYSC final clearance is stressing my life out and eating my hours.

**Review by KoneeVibes — CHANGES_REQUESTED** [review]
Please there are alot of issues with your PR.
First, the UI is not anywhere close to what we have on Figma. Please you have to clean that up. Also you've totally abandoned our coding convention in writing your code, you already know that we have row/column components etc. why did you go on to write your own flexes, up to the point that you even used inline styling in some of it. It is not scalable at all. Please when will you be able to have a cleanup session with me this weekend so we can clear this out, it's really alot and it's sad that it took this while to resolve.

**Comment by Newton-Ephraim** [comment]
chieee

**Review by KoneeVibes — APPROVED** [review]
Please pull and see how I have cleaned this up so that you will understand the payload et al to pass to the endpoint. In that process, you will also add the spinner to the form submit button as well as an error message.

**Pull request merged**
